# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)
  desc "Release new version and deploy to Sparkle"
  lane :release do
    increment_build_number
    sh("rm -r ~/Library/Caches/Sparkle_generate_appcast/")
    sh("rm ../../updates/*")
    build_app(scheme: "Conferences-Release",
          configuration: "Release",
          workspace: "Conferences.xcworkspace",
          output_directory: "../updates",
          toolchain: "org.swift.5020190129a")
    sh("cd ../../updates && zip -r Conferences.zip Conferences.app")
    sh("rm -r ../../updates/Conferences.app/")
    sh("mv ../../updates/Conferences.app.dSYM.zip ../../")
    sh("./../Pods/Sparkle/bin/generate_appcast ../../updates/")
    sh("eval $(docker-machine env conference-server)")
    sh("docker cp ../../updates conference-server_server_1:/app/Public/")
  end
end
