# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)
  desc "Release new version"
    lane :release do |options|
      type = options[:type]

      if type != "release" && type != "alpha"
        UI.user_error!("Wrong release type use: alpha or release")
      end

      build
      
      build_number = get_build_number(xcodeproj: "Conferences.xcodeproj")
      version = get_version_number(xcodeproj: "Conferences.xcodeproj")
      
      if type == "release"
        tag = version
      else 
        tag = version + "-" + type + build_number
      end
      
      filename = "Conferences_v" + tag + ".zip"

      #clean Releases/
      sh("mv ../Releases/Conferences.app.dSYM.zip ../../")
      sh("rm ../Releases/Conferences_latest.zip")
      sh("cd ../Releases && zip -r" + " " + filename + " " + "Conferences.app")
      sh("rm -r ../Releases/Conferences.app")
      
      puts "All done"
      puts "Tag: " + tag
    end

    desc "Build new release version"
    lane :build  do
      increment_build_number
      build_app(scheme: "Conferences",
            configuration: "Release",
            workspace: "Conferences.xcworkspace",
            output_directory: "Releases")
    end
